name: Deploy to Juno
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Deploy to Juno
        uses: junobuild/juno-action@main
        with:
          args: hosting deploy
          config: ./juno.config
        env:
          JUNO_SATELLITE_ID: ${{ secrets.JUNO_SATELLITE_ID }}
